name: Core
version: ${project.version}
main: dev.dankom.Start
depend:
  - HeadDatabase
  - ProtocolLib
  - PlaceholderAPI
commands:
  setRank:
  rank:
  cosmetics:
  eco:
  guild:
  g:
  prestige:
  lobby:
  profile:
  f:
  friend:
  whisper:
  msg:
